// eFondaMental Platform - Questionnaire Service
// Typed service for handling specific questionnaire responses

import { createClient } from '@/lib/supabase/server';
import {
  AsrmResponse,
  AsrmResponseInsert,
  QidsResponse,
  QidsResponseInsert,
  MdqResponse,
  MdqResponseInsert,
  BipolarDiagnosticResponse,
  BipolarDiagnosticResponseInsert,
  OrientationResponse,
  OrientationResponseInsert,
} from '@/lib/types/database.types';
import {
  ASRM_DEFINITION,
  QIDS_DEFINITION,
  MDQ_DEFINITION,
  QuestionnaireDefinition
} from '@/lib/constants/questionnaires';

// ============================================================================
// SHARED TYPES
// ============================================================================

export type PendingQuestionnaire = QuestionnaireDefinition & {
  visit_id: string;
  composite_id: string; 
};

// ============================================================================
// PENDING TASKS
// ============================================================================

export async function getPendingQuestionnaires(
  patientId: string
): Promise<PendingQuestionnaire[]> {
  const supabase = await createClient();

  // 1. Get active visits for patient
  const { data: visits, error } = await supabase
    .from('visits')
    .select('id, visit_type')
    .eq('patient_id', patientId)
    .in('status', ['scheduled', 'in_progress']);

  if (error) throw error;
  if (!visits || visits.length === 0) return [];

  const tasks: PendingQuestionnaire[] = [];

  for (const visit of visits) {
    // Logic depends on visit type
    // For now, we assume 'screening' visits require ASRM, QIDS, MDQ
    if (visit.visit_type === 'screening') {
      // Check ASRM
      const asrm = await getAsrmResponse(visit.id);
      if (!asrm) {
        tasks.push({
          ...ASRM_DEFINITION,
          visit_id: visit.id,
          composite_id: `${visit.id}_${ASRM_DEFINITION.code}`
        });
      }

      // Check QIDS
      const qids = await getQidsResponse(visit.id);
      if (!qids) {
        tasks.push({
          ...QIDS_DEFINITION,
          visit_id: visit.id,
          composite_id: `${visit.id}_${QIDS_DEFINITION.code}`
        });
      }

      // Check MDQ
      const mdq = await getMdqResponse(visit.id);
      if (!mdq) {
        tasks.push({
          ...MDQ_DEFINITION,
          visit_id: visit.id,
          composite_id: `${visit.id}_${MDQ_DEFINITION.code}`
        });
      }
    }
  }

  return tasks;
}

// ============================================================================
// ASRM (Altman Self-Rating Mania Scale)
// ============================================================================

export async function getAsrmResponse(
  visitId: string
): Promise<AsrmResponse | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('responses_asrm')
    .select('*')
    .eq('visit_id', visitId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

export async function saveAsrmResponse(
  response: AsrmResponseInsert
): Promise<AsrmResponse> {
  const supabase = await createClient();
  
  // Calculate interpretation
  const totalScore = 
    response.q1 + response.q2 + response.q3 + response.q4 + response.q5;
  
  const interpretation = totalScore >= 6 
    ? "Symptômes maniaques/hypomaniaques" 
    : "Pas de symptômes maniaques";

  const { data, error } = await supabase
    .from('responses_asrm')
    .upsert({
      ...response,
      interpretation // Note: total_score is generated by DB
    }, { onConflict: 'visit_id' })
    .select()
    .single();

  if (error) throw error;
  return data;
}

// ============================================================================
// QIDS-SR16
// ============================================================================

export async function getQidsResponse(
  visitId: string
): Promise<QidsResponse | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('responses_qids_sr16')
    .select('*')
    .eq('visit_id', visitId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

export async function saveQidsResponse(
  response: QidsResponseInsert
): Promise<QidsResponse> {
  const supabase = await createClient();

  // Calculate Score
  const sleepScore = Math.max(response.q1, response.q2, response.q3, response.q4);
  const appetiteScore = Math.max(response.q6, response.q7, response.q8, response.q9);
  const psychomotorScore = Math.max(response.q15, response.q16);
  
  const totalScore = 
    sleepScore + 
    response.q5 + 
    appetiteScore + 
    response.q10 + 
    response.q11 + 
    response.q12 + 
    response.q13 + 
    response.q14 + 
    psychomotorScore;

  let interpretation = "Pas de dépression";
  if (totalScore >= 21) interpretation = "Dépression très sévère";
  else if (totalScore >= 16) interpretation = "Dépression sévère";
  else if (totalScore >= 11) interpretation = "Dépression modérée";
  else if (totalScore >= 6) interpretation = "Dépression légère";

  const { data, error } = await supabase
    .from('responses_qids_sr16')
    .upsert({
      ...response,
      total_score: totalScore,
      interpretation
    }, { onConflict: 'visit_id' })
    .select()
    .single();

  if (error) throw error;
  return data;
}

// ============================================================================
// MDQ (Mood Disorder Questionnaire)
// ============================================================================

export async function getMdqResponse(
  visitId: string
): Promise<MdqResponse | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('responses_mdq')
    .select('*')
    .eq('visit_id', visitId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

export async function saveMdqResponse(
  response: MdqResponseInsert
): Promise<MdqResponse> {
  const supabase = await createClient();

  // Calculate Screening Result
  // POSITIF si (Q1≥7) ET (Q2=oui) ET (Q3=problème moyen ou sérieux)
  const q1Count = [
    response.q1_1, response.q1_2, response.q1_3, response.q1_4, response.q1_5,
    response.q1_6, response.q1_7, response.q1_8, response.q1_9, response.q1_10,
    response.q1_11, response.q1_12, response.q1_13
  ].filter(Boolean).length;

  const isPositive = 
    q1Count >= 7 && 
    response.q2 === true && 
    (response.q3 === 2 || response.q3 === 3);

  const { data, error } = await supabase
    .from('responses_mdq')
    .upsert({
      ...response,
      positive_screen: isPositive
    }, { onConflict: 'visit_id' })
    .select()
    .single();

  if (error) throw error;
  return data;
}

// ============================================================================
// Bipolar Diagnostic
// ============================================================================

export async function getDiagnosticResponse(
  visitId: string
): Promise<BipolarDiagnosticResponse | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('responses_bipolar_diagnostic')
    .select('*')
    .eq('visit_id', visitId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

export async function saveDiagnosticResponse(
  response: BipolarDiagnosticResponseInsert
): Promise<BipolarDiagnosticResponse> {
  const supabase = await createClient();
  const user = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from('responses_bipolar_diagnostic')
    .upsert({
      ...response,
      completed_by: user.data.user?.id
    }, { onConflict: 'visit_id' })
    .select()
    .single();

  if (error) throw error;
  return data;
}

// ============================================================================
// Orientation (Expert Center)
// ============================================================================

export async function getOrientationResponse(
  visitId: string
): Promise<OrientationResponse | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('responses_orientation')
    .select('*')
    .eq('visit_id', visitId)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

export async function saveOrientationResponse(
  response: OrientationResponseInsert
): Promise<OrientationResponse> {
  const supabase = await createClient();
  const user = await supabase.auth.getUser();

  const { data, error } = await supabase
    .from('responses_orientation')
    .upsert({
      ...response,
      completed_by: user.data.user?.id
    }, { onConflict: 'visit_id' })
    .select()
    .single();

  if (error) throw error;
  return data;
}
