-- Add item notes to MEM-III Spatial Span responses table
ALTER TABLE responses_mem3_spatial 
ADD COLUMN IF NOT EXISTS odirect_1_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_2_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_3_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_4_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_5_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_6_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_7_note INTEGER,
ADD COLUMN IF NOT EXISTS odirect_8_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_1_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_2_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_3_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_4_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_5_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_6_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_7_note INTEGER,
ADD COLUMN IF NOT EXISTS inverse_8_note INTEGER;
