-- Migration: Remove columns q11 to q30 from schizophrenia_isa table
-- Date: 2026-02-13
-- Description: Removes the columns q11 to q30 from the schizophrenia_isa table

-- Remove columns q11 to q30
ALTER TABLE public.schizophrenia_isa 
 DROP COLUMN IF EXISTS q11, DROP COLUMN IF EXISTS q12, DROP COLUMN IF EXISTS q13, DROP COLUMN IF EXISTS q14, DROP COLUMN IF EXISTS q15, DROP COLUMN IF EXISTS q16, DROP COLUMN IF EXISTS q17, DROP COLUMN IF EXISTS q18, DROP COLUMN IF EXISTS q19, DROP COLUMN IF EXISTS q20, DROP COLUMN IF EXISTS q21, DROP COLUMN IF EXISTS q22, DROP COLUMN IF EXISTS q23, DROP COLUMN IF EXISTS q24, DROP COLUMN IF EXISTS q25, DROP COLUMN IF EXISTS q26, DROP COLUMN IF EXISTS q27, DROP COLUMN IF EXISTS q28, DROP COLUMN IF EXISTS q29, DROP COLUMN IF EXISTS q30;